name: Importer

on:
    workflow_dispatch:

jobs:
    importer:
        name: "Import-Run"
        runs-on: ubuntu-latest
        environment: importer-lbgsandbox
        env:
            JAMFTF_JPRO_TENANT_ID: ${{ vars.JAMFTF_JPRO_TENANT_ID }}
            JPRO_CLIENT_ID: ${{ secrets.JPRO_CLIENT_ID }}
            JPRO_CLIENT_SECRET: ${{ secrets.JPRO_CLIENT_SECRET }}
            JAMFTF_CONFIG_FP: ${{ vars.JAMFTF_CONFIG_FP }}
            JAMFTF_OUTPUT_DIR: ${{ vars.JAMFTF_OUTPUT_DIR }}
            JAMFTF_DEBUG_MODE: false
            
        steps:
            - name: "Checkout"
              uses: actions/checkout@v4.1.1


            - name: List repository contents
              run: echo 
