name: Importer

on:
    workflow_dispatch:

jobs:
    importer:
        name: "Import-Run"
        runs-on: ubuntu-latest
        env:
            JAMFTF_JPRO_TENANT_ID: ${{ secrets.jamftf_jpro_tenant_id }}
            JPRO_CLIENT_ID: ${{ secrets.jpro_client_id }}
            JPRO_CLIENT_SECRET: ${{ secrets.jpro_client_secret }}
            JAMFTF_CONFIG_FP: ${{ secrets.jamftf_config_fp }}
            JAMFTF_OUTPUT_DIR: ${{ secrets.jamftf_output_dir }}
            JAMFTF_DEBUG_MODE: false
            
        steps:
            - name: "Checkout"
              uses: actions/checkout@v4.1.1


            - name: List repository contents
              run: ls -R
