name: Import Config From File

on:
    workflow_dispatch:

jobs:
    importer:
        name: "Import-Run"
        runs-on: ubuntu-latest
        environment: importer-lbgsandbox
        env:
            JP_TENANT_NAME: ${{ vars.JP_TENANT_NAME }}
            JP_CLIENT_ID: ${{ secrets.JP_CLIENT_ID }}
            JP_CLIENT_SECRET: ${{ secrets.JP_CLIENT_SECRET }}
            WORKING_DIR: ${{ vars.WORKING_DIR }}

        steps:
            - name: "Checkout"
              uses: actions/checkout@v4.1.1
              with:
                path: "deploymenttheory/terraform-importer-jamfpro"

            - name: Set up Python
              uses: actions/setup-python@v4
              with: 
                python-version: '3.x'

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install git+https://github.com/thejoeker12/jamfpy-python-sdk-jamfpro@v1.1.1
                pip install git+https://${{ secrets.PAT_TOKEN }}@github.com/deploymenttheory/jamftf-python-terraform-importer@v0.2.1
                pip install requests

            - name: Run Python script
              run: python scripts/import_via_config_file.py

            - name: Install Terraform
              uses: hashicorp/setup-terraform@v3.1.2
              with:
                terraform_version: latest
                cli_config_credentials_token: ${{ secrets.TF_API_KEY }}

            - name: Terraform fmt
              run: |
                cd importer_working_dir/
                terraform init
                terraform fmt
                terraform plan --generate-config-out="out.tf"


            - name: Commit back to Repo
              run: |
                git config --global user.email "action@github.com"
                git config --global user.name "Github Action"
                git add importer_working_dir/
                git commit -m "Uploading output files"
                git push


            - name: Checkout2
              uses: actions/checkout@v4
              with:
                repository: "deploymenttheory/terraform-demo-jamfpro-v2"
                path: "deploymenttheory/terraform-demo-jamfpro-v2"
                token: ${{ secrets.PAT_TOKEN }}


