name: Importer

on:
    push:
      branches:
        - '*'
    workflow_dispatch:

jobs:
    importer:
        name: "Import-Run"
        runs-on: ubuntu-latest
        environment: importer-lbgsandbox
        env:
            JAMFTF_JPRO_TENANT_ID: ${{ vars.JAMFTF_JPRO_TENANT_ID }}
            JPRO_CLIENT_ID: ${{ secrets.JPRO_CLIENT_ID }}
            JPRO_CLIENT_SECRET: ${{ secrets.JPRO_CLIENT_SECRET }}
            JAMFTF_CONFIG_FP: ${{ vars.JAMFTF_CONFIG_FP }}
            JAMFTF_OUTPUT_DIR: ${{ vars.JAMFTF_OUTPUT_DIR }}
            JAMFTF_DEBUG_MODE: false
            
        steps:
            - name: "Checkout"
              uses: actions/checkout@v4.1.1

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.x'

            - name: Configure Git credentials
              env:
                PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
              run: |
                git config --global url."https://${PERSONAL_ACCESS_TOKEN}@github.com/".insteadOf "https://github.com/"

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install git+https://github.com/deploymenttheory/jamftf-python-terraform-importer@latest
                pip install git+https://github.com/thejoeker12/jamfpy@latest
                pip install -r scripts/requirements.txt

            - name: Run Python script
              run: python scripts/import_via_config_file.py